services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.0.0
    container_name: mealie
    restart: always
    ports:
      - "127.0.0.1:9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - data:/app/data/
    env_file: .env
volumes:
  data:
