---
name: mealie
working_dir: docker/mealie
---
name: atuin
working_dir: docker/atuin
env_files:
  - secrets.enc.env
---
name: uptime-kuma
working_dir: docker/uptime-kuma
---
name: karakeep
working_dir: docker/karakeep
---
name: dozzle
working_dir: docker/dozzle-agent
env_files:
  - public.enc.env
---
name: it-tools
working_dir: docker/it-tools
