---
name: pocket-id
working_dir: docker/pocket-id
env_files:
  - secrets.enc.env
---
name: headscale
working_dir: docker/headscale
---
name: dozzle
working_dir: docker/dozzle-agent
env_files:
  - private.enc.env
