---
name: glance
working_dir: docker/glance
external_secrets:
  GLANCE_DOMAIN: "arn:aws:secretsmanager:us-east-1:913105552974:secret:glance-jxmiOS/DOMAIN"
  GLANCE_SPEEDTEST_URL: "arn:aws:secretsmanager:us-east-1:913105552974:secret:glance-jxmiOS/SPEEDTEST_URL"
  GLANCE_SPEEDTEST_API_TOKEN: "arn:aws:secretsmanager:us-east-1:913105552974:secret:glance-jxmiOS/SPEEDTEST_API_TOKEN"
---
name: speedtest
working_dir: docker/speedtest
external_secrets:
  SPEEDTEST_APP_KEY: "arn:aws:secretsmanager:us-east-1:913105552974:secret:speedtest-G92iOW/APP_KEY"
---
name: mealie
working_dir: docker/mealie
external_secrets:
  MEALIE_URL: "arn:aws:secretsmanager:us-east-1:913105552974:secret:mealie-hwGLDg/URL"
  MEALIE_EMAIL: "arn:aws:secretsmanager:us-east-1:913105552974:secret:mealie-hwGLDg/EMAIL"
  MEALIE_SMTP_PASS: "arn:aws:secretsmanager:us-east-1:913105552974:secret:mealie-hwGLDg/SMTP_PASS"
  MEALIE_OIDC_URL: "arn:aws:secretsmanager:us-east-1:913105552974:secret:mealie-hwGLDg/OIDC_URL"
  MEALIE_OIDC_ID: "arn:aws:secretsmanager:us-east-1:913105552974:secret:mealie-hwGLDg/OIDC_ID"
  MEALIE_OIDC_SECRET: "arn:aws:secretsmanager:us-east-1:913105552974:secret:mealie-hwGLDg/OIDC_SECRET"
