services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.1.0@sha256:f8ed26e8012ae60d5320735dcdecf7347778e2a31c69a147f5c030e017cb32d9
    container_name: pocket-id
    restart: unless-stopped
    env_file: secrets.enc.env
    ports:
      - 127.0.0.1:1411:1411
    volumes:
      - data:/app/data
    healthcheck:
      test: "curl -f http://pocket-id:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
volumes:
  data:
