services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.18.0@sha256:323e7ef5bfacf7cf32f22f3d10ccdf48e0c97c94d67e7e40b0b996830deb5165
    container_name: pocket-id
    restart: unless-stopped
    env_file: secrets.enc.env
    ports:
      - 127.0.0.1:1411:1411
    volumes:
      - data:/app/data
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
volumes:
  data:
