apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work-pvc
  namespace: adguard
  labels:
    app: adguard-home
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf-pvc
  namespace: adguard
  labels:
    app: adguard-home
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
