services:
  headscale:
    image: docker.io/headscale/headscale:v0.29.2@sha256:d337f1be4a9155b330aa9077bf6c82d24ff0581b8e69390ebc6d7c623bb339ce
    container_name: headscale
    restart: unless-stopped
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:9090:9090'
    volumes:
      - '/opt/headscale/conf:/etc/headscale'
      - '/opt/headscale/lib:/var/lib/headscale'
      - '/opt/headscale/run:/var/run/headscale'
    command: serve
