services:
  postgres:
    image: postgres:16-alpine
    container_name: linkwarden-db
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:v2.11.3
    container_name: linkwarden
    restart: unless-stopped
    ports:
      - "127.0.0.1:3300:3000"
    volumes:
      - data:/data/data
    depends_on:
      - postgres
      - meilisearch
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
  meilisearch:
    image: getmeili/meilisearch:v1.15.2
    container_name: linkwarden-search
    restart: unless-stopped
    volumes:
      - meili:/meili_data
    env_file: .env
volumes:
  postgres:
  data:
  meili:
