services:
  glance:
    container_name: glance
    image: docker.io/glanceapp/glance:v0.8.5@sha256:32ab73d80f2b8b5fb0735b0431deb36b93fbb6b2fb43592449b0178c8b83e350
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - secrets.enc.env
