services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:2.8.0@sha256:3fa942a440ae7cc62c115f4f931d4c53ed2c185eb0172248f61478c3e9ba3598
    container_name: babybuddy
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - secrets.enc.env
    volumes:
      - data:/config
    restart: unless-stopped
volumes:
  data:
    driver: local
