services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:2.8.0@sha256:81ffeb763cbcb9f8b9807abca05e5c46170bd2777a88f441ec35b79b3e6dc813
    container_name: babybuddy
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - secrets.enc.env
    volumes:
      - data:/config
    restart: unless-stopped
volumes:
  data:
    driver: local
