services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:2.8.0@sha256:f48bfde0689a3403b3dca27c4d956fdab01ced7db2918cbee800cc0dca129964
    container_name: babybuddy
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - TZ=America/Chicago
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,https://babybuddy.cleek.xyz
    volumes:
      - data:/config
    restart: unless-stopped
volumes:
  data:
    driver: local
