services:
  dozzle:
    container_name: dozzle
    image: docker.io/amir20/dozzle:v10.10.0@sha256:2875e3c1f31f2244ee99d6067b53852b30666b3e2fb293d179bc8be94b1da5eb
    volumes:
      - ./certs:/certs
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:8888:8080
    env_file:
      - secrets.enc.env
