services:
  dozzle:
    container_name: dozzle
    image: docker.io/amir20/dozzle:v10.1.2@sha256:ca18ce13851bb5b39b4296df498eeedc59849e833a6dc43e94cb04435435a9f2
    volumes:
      - ./certs:/certs
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:8888:8080
    env_file:
      - secrets.enc.env
