services:
  dozzle:
    container_name: dozzle
    image: docker.io/amir20/dozzle:v10.0.2@sha256:f1f82c27077f39c0a563f24e9929d36f23bdf9c1590217794a08ea49677201cf
    volumes:
      - ./certs:/certs
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:8888:8080
    environment:
      - DOZZLE_REMOTE_AGENT=${DOZZLE_AGENT}
      - DOZZLE_CERT=/certs/cert.enc.pem
      - DOZZLE_KEY=/certs/key.enc.pem
      - DOZZLE_NO_ANALYTICS=true
