services:
  dozzle-agent:
    image: docker.io/amir20/dozzle:v10.6.11@sha256:bc1ee4ba8d66c7fc0d03823a78486165fb219809f79eaf54cecf3114d647ab14
    container_name: dozzle-agent
    command: agent
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./certs:/certs
    ports:
      - 7007:7007
    environment:
      - DOZZLE_CERT=${DOZZLE_CERT}
      - DOZZLE_KEY=${DOZZLE_KEY}
      - DOZZLE_NO_ANALYTICS=${DOZZLE_NO_ANALYTICS}
      - DOZZLE_HOSTNAME=${DOZZLE_HOSTNAME}
