services:
  dozzle-agent:
    image: docker.io/amir20/dozzle:v10.5.1@sha256:2f8d5c2b6181533a58246313b1d840a69ae04e6c1010e2f6bb52c2228342b443
    container_name: dozzle-agent
    command: agent
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./certs:/certs
    ports:
      - 7007:7007
    environment:
      - DOZZLE_CERT=${DOZZLE_CERT}
      - DOZZLE_KEY=${DOZZLE_KEY}
      - DOZZLE_NO_ANALYTICS=${DOZZLE_NO_ANALYTICS}
      - DOZZLE_HOSTNAME=${DOZZLE_HOSTNAME}
