services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.9.2@sha256:57713693dceca9a124f00f165eaf8f5c41de757e7f63f8a7b80625488605dc61
    container_name: mealie
    restart: always
    ports:
      - 127.0.0.1:9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - data:/app/data/
    env_file:
      - secrets.enc.env
volumes:
  data:
