services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.27.0@sha256:ba24b88462380fb59a6c7d04c6d9e607e0b6b04e31306592181186bcdab1952b
    container_name: mealie
    restart: always
    ports:
      - 127.0.0.1:9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - data:/app/data/
    env_file:
      - secrets.enc.env
volumes:
  data:
