services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.25.1@sha256:6066c29eca95a6cac640ecadf734799522f3b646ee4a714e0d13ce795d989ba2
    container_name: mealie
    restart: always
    ports:
      - 127.0.0.1:9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - data:/app/data/
    env_file:
      - secrets.enc.env
volumes:
  data:
