services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:2.7.1
    container_name: babybuddy
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - data:/config
    env_file: .env
volumes:
  data:
