services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.7.4@sha256:040b2fed8f7f6b7405f9b4b26348b4656355e4d4ed0852b8e966d453dd6635cc
    container_name: immich_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    volumes:
      - ${UPLOAD_LOCATION:-/tmp}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - secrets.enc.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.4-cuda@sha256:38e5db5a7c65ec822b7a18d2ece4c49c913e15b7eb35f11515889e7720e00518
    container_name: immich_machine_learning
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - /mnt/immich-media/immich_model-cache:/cache
    env_file:
      - secrets.enc.env
    restart: always
    healthcheck:
      disable: false
  redis:
    image: docker.io/valkey/valkey:9@sha256:4503e204c900a00ad393bec83c8c7c4c76b0529cd629e23b34b52011aefd1d27
    container_name: immich_redis
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_USER: ${DB_USERNAME:-password123}
      POSTGRES_DB: ${DB_DATABASE_NAME:-db}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION:-/tmp}:/var/lib/postgresql/data
    restart: always
