services:
  uptime-kuma:
    container_name: uptime
    image: docker.io/louislam/uptime-kuma:2.1.0@sha256:da418b1f5655c12d2d62aa3d189117bfad5d83c2ab99bb3e82b2eaaf5246bbc1
    restart: unless-stopped
    volumes:
      - data:/app/data
      - /run/user/1000/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:3001:3001"
volumes:
  data:
