services:
  uptime-kuma:
    container_name: uptime
    image: docker.io/louislam/uptime-kuma:2.5.6@sha256:9912da7d7d9b6ddc0c2d904beb84d24689c1ed9c33b81419eb9008663a92a329
    restart: unless-stopped
    volumes:
      - data:/app/data
      - /run/user/1000/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:3001:3001"
volumes:
  data:
