services:
  uptime-kuma:
    container_name: uptime
    image: docker.io/louislam/uptime-kuma:2.2.0@sha256:85d68948704fcadc7438f45c9f2666ef2239b5b84073479e1c5bc4d4d8b6d17c
    restart: unless-stopped
    volumes:
      - data:/app/data
      - /run/user/1000/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:3001:3001"
volumes:
  data:
